add mit side intrgration and entity mapping file
ml4ai/ASKEM-TA1-DataModel pull request #2
Opened 2023-04-06 03:30 UTC by Tranway1

2023-04-06 16:12 UTC, enoriega requested changes

2023-04-06 16:12 UTC, enoriega commented on askem_extractions/importers/mit.py
@Tranway1 , in general this function looks good. Before merging we need to decouple the parts that read the MIT extractions from the code that merges them with AZ extractions.

The reason for this is that it is plausible that you want to load MIT extractions without having AZ extractions and the mapping and if this function requires them, you can't use it.

The pseudo code of this workflow could be something like this:
```python
mit_extractions = import_mit(Path("mit_data.json"))
az_extractions = import_arizona(Path("az_data.json"))

merged_extractions = merge_collections(mit_extractions, az_extractions, Path("mapping.txt"))
```

I left comments with my suggestions on the relevant lines

2023-04-06 16:12 UTC, enoriega commented on askem_extractions/importers/mit.py
> +def import_mit(a_path: Path, m_path: Path, map_path: Path) -> ExtractionsCollection:
I suggest breaking up the functionality into two functions:

- `import_mit` will only be responsible to parse your output data format (`m_path`)
- A new function: `merge_collections` that takes AZ and MIT's imported data and merges it using the map (`a_path` and `map_path`)

2023-04-06 16:12 UTC, enoriega commented on askem_extractions/importers/mit.py
> +    from_json = ExtractionsCollection.from_json(a_path)
This could go in `merge_collections`

2023-04-06 16:12 UTC, enoriega commented on askem_extractions/importers/mit.py
> +        mappings = mapping_file.readlines()
These could go in `merge_collections`

2023-04-06 16:12 UTC, enoriega commented on askem_extractions/importers/mit.py
> +    from_json.save_json("TA1-integration.json")
This could be the return value of `merge_collections`

2023-04-06 16:12 UTC, enoriega commented on askem_extractions/importers/mit.py
> +                            vs.variable.column.append(column)
This block could probably be the only part remaining in this function and the outer loop could go on the `merge_collections`

2023-04-06 16:12 UTC, enoriega commented on askem_extractions/importers/mit.py
> +            entry_a_id = [k for k, v in mapping_dict.items() if v == entry_b_id][0]
This outer block should probably go in `merge_collections`

2023-04-06 16:12 UTC, enoriega commented on askem_extractions/importers/mit.py
> +    import_mit(Path("../../examples/temp.json"), Path("../../examples/mit_extraction.json"), Path("../../examples/mapping.txt"))
Can you delete this block? It is already included in `usage.py`

2023-04-08 02:32 UTC, Tranway1 commented
Please check the refactored code

2023-04-09 00:31 UTC, enoriega approved these changes
Looks good to me!

2023-04-09 00:31 UTC, merged

2023-04-09 00:38 UTC, enoriega commented
@Tranway1 Thanks! This is merged into main. I think we are ready to share it with TA4 folks